name: Update Profile README

on:
  schedule:
    # Executa a cada 6 horas (ajuste o cron conforme necessário)
    # Formato: minuto hora dia(mês) mês dia(semana)
    # *: qualquer valor
    # */6: a cada 6 unidades (neste caso, horas)
    - cron: '0 */6 * * *'
  workflow_dispatch: # Permite executar manualmente pela aba Actions
  push:
    branches:
      - main 
    paths:
      - '.github/workflows/update_readme.yml'
      - 'update_readme.py'
      - 'requirements.txt'

jobs:
  build:
    runs-on: ubuntu-latest # Usa a última versão estável do Ubuntu como ambiente

    steps:
      - name: Checkout Repository # Baixa o código do seu repositório
        uses: actions/checkout@v4 # Ação oficial para checkout

      - name: Set up Python # Configura o ambiente Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x' # Use Python 3 (versão específica se necessário)

      - name: Install Dependencies # Instala as bibliotecas do requirements.txt
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Update Script # Executa seu script Python
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Passa o token como variável de ambiente
        run: python update_readme.py

      - name: Commit and Push Changes # Faz o commit e push do README.md atualizado
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'chore: Atualiza README com últimas atividades' # Mensagem do commit
          commit_user_name: 'github-actions[bot]' # Nome do autor do commit
          commit_user_email: 'github-actions[bot]@users.noreply.github.com' # Email do autor
          commit_author: 'github-actions[bot] <github-actions[bot]@users.noreply.github.com>'
          file_pattern: 'README.md update_readme.log' # Arquivos a serem commitados (README e log)
          push_options: '--force' # Opcional: Força o push se necessário (use com cautela)
