name: Update Profile README

on:
  schedule:
    - cron: '0 */6 * * *' # Ajustado para o cron do seu primeiro exemplo, pode usar '0 0 * * *' se preferir
  workflow_dispatch:
  push:
    branches:
      - main # Ou master
    paths:
      - '.github/workflows/update_readme.yml'
      - 'update_readme.py'
      - 'requirements.txt'

jobs:
  build: # Renomeado para build como no seu primeiro exemplo, pode ser update-readme também
    runs-on: ubuntu-latest
    # Adicione esta seção de permissões:
    permissions:
      contents: write # Permite que o job faça checkout e push

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt # Usando requirements.txt

      - name: Run Update Script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python update_readme.py

      - name: Commit and Push Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'chore: Atualiza README com últimas atividades'
          commit_user_name: 'github-actions[bot]'
          commit_user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_author: 'github-actions[bot] <github-actions[bot]@users.noreply.github.com>'
          file_pattern: 'README.md update_readme.log'
          # push_options: '--force' # Removido temporariamente para teste, pode não ser necessário
